spring:
  doc:
    snippets:
      output-dir: build/generated-snippets
logging:
  level:
    root: DEBUG
app:
  base-url: http://localhost:8080

oauth2:
  client:
    registration:
      line:
        client-id: <LINE_CLIENT_ID>
        client-secret: <LINE_CLIENT_SECRET>
        redirect-uri: "${app.base-url}/api/v1/auth/login/oauth2/line"
        authorization-grant-type: authorization_code
        scope: profile, openid
    provider:
      line:
        authorization-uri: https://access.line.me/oauth2/v2.1/authorize
        token-uri: https://api.line.me/oauth2/v2.1/token
